apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: music
  labels:
    app: chat-app
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: chat-app

